# Generated by Django 4.0.5 on 2022-07-04 09:02

from django.db import migrations
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_client_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client',
                     'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', registration.models.UserManager()),
            ],
        ),
    ]
